name: "Lockdown"

on:
  pull_request_target:
    types: opened
  schedule:
    - cron: "0 * * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          pr-comment: "🔒 Pull requests have been locked on this repository."
